var myApp=angular.module("myApp",["userModule","hardModule","ngRoute","ngAnimate"]);
myApp.config(function ($routeProvider) {
    $routeProvider
        .when('/findAll',{
            templateUrl:'html/allUser.html',
            controller:"findAll"
        })
         .when('/login',{
            templateUrl:'html/login.html',
            controller:"login"
        })
         .when('/cpu',{
            templateUrl:'html/cpu.html',
            controller:"cpu"
        })
         .when('/cpus',{
            templateUrl:'html/cpus.html',
            controller:"cpus"
        })
         .when('/disk',{
            templateUrl:'html/disk.html',
            controller:"disk"
        })
         .when('/memory',{
            templateUrl:'html/memory.html',
            controller:"memory"
        })
         .when('/swap',{
            templateUrl:'html/swap.html',
            controller:"swap"
        })
        .otherwise({
            redirectTo:'/login'
        })
});